// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpI9GOM8Vp2ir_q69bSd8btVVJDRVxZg',
    appId: '1:647965852476:web:d6535bcad2fdeb50789439',
    messagingSenderId: '647965852476',
    projectId: 'librifyhub',
    authDomain: 'librifyhub.firebaseapp.com',
    storageBucket: 'librifyhub.firebasestorage.app',
    measurementId: 'G-8M1C49M99V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZOVsizJbLVYLPxetQE_f9t782sswaPU',
    appId: '1:647965852476:android:673e0dbdd838f2f1789439',
    messagingSenderId: '647965852476',
    projectId: 'librifyhub',
    storageBucket: 'librifyhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJFa5g4FmM_ys2kZ4hnlmRzhbM_wJ4IQ',
    appId: '1:647965852476:ios:6b93b71e9566cb23789439',
    messagingSenderId: '647965852476',
    projectId: 'librifyhub',
    storageBucket: 'librifyhub.firebasestorage.app',
    iosBundleId: 'com.example.librifyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaJFa5g4FmM_ys2kZ4hnlmRzhbM_wJ4IQ',
    appId: '1:647965852476:ios:6b93b71e9566cb23789439',
    messagingSenderId: '647965852476',
    projectId: 'librifyhub',
    storageBucket: 'librifyhub.firebasestorage.app',
    iosBundleId: 'com.example.librifyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpI9GOM8Vp2ir_q69bSd8btVVJDRVxZg',
    appId: '1:647965852476:web:a238e0c9cb260f17789439',
    messagingSenderId: '647965852476',
    projectId: 'librifyhub',
    authDomain: 'librifyhub.firebaseapp.com',
    storageBucket: 'librifyhub.firebasestorage.app',
    measurementId: 'G-S063KLYSKQ',
  );
}
